package com.veritas.reader.ui

import android.net.Uri
import com.veritas.reader.*
import java.io.File

data class VeritasPendingImport(
    val uri: Uri,
    val name: String,
    val mimeType: String,
    val sizeBytes: Long,
    val isPdf: Boolean,
    val pageCount: Int,
    val pdfOptions: PdfImportOptions,
    val textOptions: TextImportOptions,
    val isPptx: Boolean = false,
    val pptxOptions: PptxImportOptions = PptxImportOptions(),
    val sourceNameHint: String? = null
)

data class ReaderUiState(
    val documents: List<SavedDocument> = emptyList(),
    val generalNotes: List<GeneralNote> = emptyList(),
    val showGeneralNotesEditor: Boolean = false,
    val generalNoteEditorTarget: GeneralNote? = null,
    val noteEditorChecklistOnStart: Boolean = false,
    val noteEditorReminderOnStart: Boolean = false,
    val noteEditorImageOnStart: Boolean = false,
    val queuedDocuments: List<SavedDocument> = emptyList(),
    val flashcards: List<FlashcardProgress> = emptyList(),
    val draftText: String = "",
    val activeDocument: ReaderDocument? = null,
    val deleteTarget: SavedDocument? = null,
    val importMessage: String? = null,
    val importInProgress: Boolean = false,
    val isOpeningDocument: Boolean = false,
    val importSourceName: String = "",
    val handledInitialShare: Boolean = false,
    val userName: String = "",
    val hasCompletedOnboarding: Boolean = false,
    val hasImportedOrOpenedDocument: Boolean = false,
    val questTourDone: Boolean = false,
    val questImportDone: Boolean = false,
    val questSpeedDone: Boolean = false,
    val questBookmarkDone: Boolean = false,
    val showConfetti: Boolean = false,
    val annotations: List<ReaderAnnotation> = emptyList(),
    val allAnnotations: List<ReaderAnnotation> = emptyList(),
    val documentNotes: Map<String, String> = emptyMap(),
    val documentTitles: Map<String, String> = emptyMap(),
    val annotationCount: Int = 0,
    val noteTargetIndex: Int? = null,
    val noteTargetIndexes: List<Int> = emptyList(),
    val noteDraft: String = "",
    val documentNoteDraft: String = "",
    val pronunciationRules: List<PronunciationRule> = emptyList(),
    val voiceSettings: VoiceSettings = VoiceSettings(),
    val narrationSettings: NarrationSettings = NarrationSettings(),
    val ttsEngines: List<TtsEngineOption> = emptyList(),
    val ttsVoices: List<TtsVoiceOption> = emptyList(),
    val voiceLoadInProgress: Boolean = false,
    val voiceMessage: String? = null,
    val readerSettings: ReaderSettings = ReaderSettings(),
    val askAiSettings: AskAiSettings = AskAiSettings(),
    val showReaderSettings: Boolean = false,
    val showPronunciationRules: Boolean = false,
    val showVoiceStudio: Boolean = false,
    val showNarrationStudio: Boolean = false,
    val showAiStudyTools: Boolean = false,
    val showOfflineStudyTools: Boolean = false,
    val showTranslationTools: Boolean = false,
    val showSleepTimerDialog: Boolean = false,
    val showBackupTools: Boolean = false,
    val showPdfImportTools: Boolean = false,
    val showSettingsHub: Boolean = false,
    val showUserManual: Boolean = false,
    val showSyncCenter: Boolean = false,
    val showAiCenter: Boolean = false,
    val showAppHealth: Boolean = false,
    val showAskAiSettings: Boolean = false,
    val showTutorial: Boolean = false,
    val showTextEditor: Boolean = false,
    val aiPromptTemplates: List<AiPromptTemplate> = emptyList(),
    val aiPromptHistory: List<AiPromptHistoryEntry> = emptyList(),
    val readingListCatalog: VeritasReadingListCatalog = VeritasReadingListCatalog(),
    val showReadingLists: Boolean = false,
    val readingHistory: List<ReadingHistoryEntry> = emptyList(),
    val showReadingHistory: Boolean = false,
    val showDocumentNotes: Boolean = false,
    val showCanvasView: Boolean = false,
    val advancedPdfOptions: PdfImportOptions = PdfImportOptions(),
    val textImportOptions: TextImportOptions = TextImportOptions(),
    val showFileBrowser: Boolean = false,
    val fileBrowserRoots: List<VeritasBrowserRoot> = emptyList(),
    val fileBrowserFiles: List<VeritasBrowserFile> = emptyList(),
    val fileBrowserLocation: VeritasBrowserLocation? = null,
    val fileBrowserBackStack: List<VeritasBrowserLocation> = emptyList(),
    val fileBrowserMessage: String? = null,
    val fileBrowserScanning: Boolean = false,
    val fileBrowserAllFilesGranted: Boolean = false,
    val backupInProgress: Boolean = false,
    val backupMessage: String? = null,
    val newRuleFind: String = "",
    val newRuleReplaceWith: String = "",
    val searchQuery: String = "",
    val searchMatches: List<Int> = emptyList(),
    val searchCursor: Int = 0,
    val documentOutline: List<VeritasDocumentOutlineEntry> = emptyList(),
    val exportInProgress: Boolean = false,
    val exportMessage: String? = null,
    val exportedAudioFile: File? = null,
    val recordMode: Boolean = false,
    val recordAwaitingDecision: Boolean = false,
    val recordStartedAt: Long = 0L,
    val recordElapsedSeconds: Long = 0L,
    val renameTarget: SavedDocument? = null,
    val renameDraft: String = "",
    val collectionTarget: SavedDocument? = null,
    val collectionDraft: String = "",
    val detailsTarget: SavedDocument? = null,
    val notificationPermissionRequested: Boolean = false,
    val editorText: String = "",
    val editorTarget: VeritasTextEditTarget? = null,
    val pendingTextDownload: Pair<String, String>? = null,
    val pendingCropUri: Uri? = null,
    val readerTrackerSnapshot: ReaderTrackerSnapshot = ReaderTrackerSnapshot.empty(),
    val pendingImport: VeritasPendingImport? = null,
    val documentReadingTimes: Map<String, Long> = emptyMap(),
    val navStack: List<VeritasScreen> = emptyList(),
    val showUpdateDialog: Boolean = false,
    val updateVersionName: String = "",
    val updateUrl: String = "",
    val updateApkUrl: String = "",
    val updateChangelog: String = "",
    val isDownloadingUpdate: Boolean = false,
    val updateDownloadProgress: Float = 0f,
    val updateDownloadError: String? = null,
    val showReleaseNotesDialog: Boolean = false,
    val releaseNotesChangelog: String = "",
    val releaseNotesVersionName: String = "",
    val pendingWidgetAction: String? = null,
    val pendingWidgetDocId: String? = null,
    val pendingWidgetNoteId: String? = null,
    val pendingImportOnStart: Boolean = false
)
